---
title: "SCP wiki data analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read}
data1 <- read.table("data-3-09-21.txt", header=T)
data2 <- read.table("tanhony_data.txt", header=T)
```

```{r preprocess1, include=F}

scp1 <- as.integer(data1$scp_number)
rating1 <- as.integer(data1$rating)
comments1 <- as.integer(data1$comments)
```

```{r preprocess2, include=F}

scp2 <- c()

for (i in 0:length(data2$SCP)) {
  str <- data2$SCP[i]
  if (length(str) > 0 && startsWith(str, "SCP-")) {
    scp2 <- append(scp2, as.integer(substring(str, 5)))
  }
}

rating2 <- as.integer(data2$Rating)
comments2 <- as.integer(data2$Comments)
```

```{r preprocess3, include=F}

group <- c()

for (i in 1:length(scp1)) {
  if (length(which(scp2 == scp1[i])) > 0) {
    group <- append(group, 2)
    
  } else {
    group <- append(group, 1)
  }
}

all.data <- data.frame(
  scp=scp1, 
  rating=rating1, 
  comments=comments1, 
  group=as.factor(group))

all.data <- subset(all.data, scp != 1)
group1 <- subset(all.data, group == 1)
group2 <- subset(all.data, group == 2)
```

# Summary 

# Calculations

## Preprocessing

```{r preprocess4}
head(all.data)
head(group1)
head(group2)
nrow(all.data)
nrow(group1)
nrow(group2)
mean(group1$rating)
mean(group2$rating)
mean(group1$rating / (group1$comments + 1))
mean(group2$rating / (group2$comments + 1))
```

## Checking linear correlation between number of comments and rating

